<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

class CountryController extends AbstractController
{
    #[Route('/api/countries', name: 'api_countries', methods: ['GET'])]
    public function getCountries(): JsonResponse
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'telephoneCode' => '+93'],
            ['name' => 'Albania', 'code' => 'AL', 'telephoneCode' => '+355'],
            ['name' => 'Algeria', 'code' => 'DZ', 'telephoneCode' => '+213'],
            ['name' => 'Andorra', 'code' => 'AD', 'telephoneCode' => '+376'],
            ['name' => 'Angola', 'code' => 'AO', 'telephoneCode' => '+244'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'telephoneCode' => '+1'],
            ['name' => 'Argentina', 'code' => 'AR', 'telephoneCode' => '+54'],
            ['name' => 'Armenia', 'code' => 'AM', 'telephoneCode' => '+374'],
            ['name' => 'Australia', 'code' => 'AU', 'telephoneCode' => '+61'],
            ['name' => 'Austria', 'code' => 'AT', 'telephoneCode' => '+43'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'telephoneCode' => '+994'],
            ['name' => 'Bahamas', 'code' => 'BS', 'telephoneCode' => '+1'],
            ['name' => 'Bahrain', 'code' => 'BH', 'telephoneCode' => '+973'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'telephoneCode' => '+880'],
            ['name' => 'Barbados', 'code' => 'BB', 'telephoneCode' => '+1'],
            ['name' => 'Belarus', 'code' => 'BY', 'telephoneCode' => '+375'],
            ['name' => 'Belgium', 'code' => 'BE', 'telephoneCode' => '+32'],
            ['name' => 'Belize', 'code' => 'BZ', 'telephoneCode' => '+501'],
            ['name' => 'Benin', 'code' => 'BJ', 'telephoneCode' => '+229'],
            ['name' => 'Bhutan', 'code' => 'BT', 'telephoneCode' => '+975'],
            ['name' => 'Bolivia', 'code' => 'BO', 'telephoneCode' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'telephoneCode' => '+387'],
            ['name' => 'Botswana', 'code' => 'BW', 'telephoneCode' => '+267'],
            ['name' => 'Brazil', 'code' => 'BR', 'telephoneCode' => '+55'],
            ['name' => 'Brunei', 'code' => 'BN', 'telephoneCode' => '+673'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'telephoneCode' => '+359'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'telephoneCode' => '+226'],
            ['name' => 'Burundi', 'code' => 'BI', 'telephoneCode' => '+257'],
            ['name' => 'Cambodia', 'code' => 'KH', 'telephoneCode' => '+855'],
            ['name' => 'Cameroon', 'code' => 'CM', 'telephoneCode' => '+237'],
            ['name' => 'Canada', 'code' => 'CA', 'telephoneCode' => '+1'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'telephoneCode' => '+238'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'telephoneCode' => '+236'],
            ['name' => 'Chad', 'code' => 'TD', 'telephoneCode' => '+235'],
            ['name' => 'Chile', 'code' => 'CL', 'telephoneCode' => '+56'],
            ['name' => 'China', 'code' => 'CN', 'telephoneCode' => '+86'],
            ['name' => 'Colombia', 'code' => 'CO', 'telephoneCode' => '+57'],
            ['name' => 'Comoros', 'code' => 'KM', 'telephoneCode' => '+269'],
            ['name' => 'Congo (Brazzaville)', 'code' => 'CG', 'telephoneCode' => '+242'],
            ['name' => 'Congo (Kinshasa)', 'code' => 'CD', 'telephoneCode' => '+243'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'telephoneCode' => '+506'],
            ['name' => 'Croatia', 'code' => 'HR', 'telephoneCode' => '+385'],
            ['name' => 'Cuba', 'code' => 'CU', 'telephoneCode' => '+53'],
            ['name' => 'Cyprus', 'code' => 'CY', 'telephoneCode' => '+357'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'telephoneCode' => '+420'],
            ['name' => 'Denmark', 'code' => 'DK', 'telephoneCode' => '+45'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'telephoneCode' => '+253'],
            ['name' => 'Dominica', 'code' => 'DM', 'telephoneCode' => '+1'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'telephoneCode' => '+1'],
            ['name' => 'Ecuador', 'code' => 'EC', 'telephoneCode' => '+593'],
            ['name' => 'Egypt', 'code' => 'EG', 'telephoneCode' => '+20'],
            ['name' => 'El Salvador', 'code' => 'SV', 'telephoneCode' => '+503'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'telephoneCode' => '+240'],
            ['name' => 'Eritrea', 'code' => 'ER', 'telephoneCode' => '+291'],
            ['name' => 'Estonia', 'code' => 'EE', 'telephoneCode' => '+372'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'telephoneCode' => '+251'],
            ['name' => 'Fiji', 'code' => 'FJ', 'telephoneCode' => '+679'],
            ['name' => 'Finland', 'code' => 'FI', 'telephoneCode' => '+358'],
            ['name' => 'France', 'code' => 'FR', 'telephoneCode' => '+33'],
            ['name' => 'Gabon', 'code' => 'GA', 'telephoneCode' => '+241'],
            ['name' => 'Gambia', 'code' => 'GM', 'telephoneCode' => '+220'],
            ['name' => 'Georgia', 'code' => 'GE', 'telephoneCode' => '+995'],
            ['name' => 'Germany', 'code' => 'DE', 'telephoneCode' => '+49'],
            ['name' => 'Ghana', 'code' => 'GH', 'telephoneCode' => '+233'],
            ['name' => 'Greece', 'code' => 'GR', 'telephoneCode' => '+30'],
            ['name' => 'Grenada', 'code' => 'GD', 'telephoneCode' => '+1'],
            ['name' => 'Guatemala', 'code' => 'GT', 'telephoneCode' => '+502'],
            ['name' => 'Guinea', 'code' => 'GN', 'telephoneCode' => '+224'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'telephoneCode' => '+245'],
            ['name' => 'Guyana', 'code' => 'GY', 'telephoneCode' => '+592'],
            ['name' => 'Haiti', 'code' => 'HT', 'telephoneCode' => '+509'],
            ['name' => 'Honduras', 'code' => 'HN', 'telephoneCode' => '+504'],
            ['name' => 'Hungary', 'code' => 'HU', 'telephoneCode' => '+36'],
            ['name' => 'Iceland', 'code' => 'IS', 'telephoneCode' => '+354'],
            ['name' => 'India', 'code' => 'IN', 'telephoneCode' => '+91'],
            ['name' => 'Indonesia', 'code' => 'ID', 'telephoneCode' => '+62'],
            ['name' => 'Iran', 'code' => 'IR', 'telephoneCode' => '+98'],
            ['name' => 'Iraq', 'code' => 'IQ', 'telephoneCode' => '+964'],
            ['name' => 'Ireland', 'code' => 'IE', 'telephoneCode' => '+353'],
            ['name' => 'Israel', 'code' => 'IL', 'telephoneCode' => '+972'],
            ['name' => 'Italy', 'code' => 'IT', 'telephoneCode' => '+39'],
            ['name' => 'Jamaica', 'code' => 'JM', 'telephoneCode' => '+1'],
            ['name' => 'Japan', 'code' => 'JP', 'telephoneCode' => '+81'],
            ['name' => 'Jordan', 'code' => 'JO', 'telephoneCode' => '+962'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'telephoneCode' => '+7'],
            ['name' => 'Kenya', 'code' => 'KE', 'telephoneCode' => '+254'],
            ['name' => 'Kiribati', 'code' => 'KI', 'telephoneCode' => '+686'],
            ['name' => 'Kuwait', 'code' => 'KW', 'telephoneCode' => '+965'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'telephoneCode' => '+996'],
            ['name' => 'Laos', 'code' => 'LA', 'telephoneCode' => '+856'],
            ['name' => 'Latvia', 'code' => 'LV', 'telephoneCode' => '+371'],
            ['name' => 'Lebanon', 'code' => 'LB', 'telephoneCode' => '+961'],
            ['name' => 'Lesotho', 'code' => 'LS', 'telephoneCode' => '+266'],
            ['name' => 'Liberia', 'code' => 'LR', 'telephoneCode' => '+231'],
            ['name' => 'Libya', 'code' => 'LY', 'telephoneCode' => '+218'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'telephoneCode' => '+423'],
            ['name' => 'Lithuania', 'code' => 'LT', 'telephoneCode' => '+370'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'telephoneCode' => '+352'],
            ['name' => 'Madagascar', 'code' => 'MG', 'telephoneCode' => '+261'],
            ['name' => 'Malawi', 'code' => 'MW', 'telephoneCode' => '+265'],
            ['name' => 'Malaysia', 'code' => 'MY', 'telephoneCode' => '+60'],
            ['name' => 'Maldives', 'code' => 'MV', 'telephoneCode' => '+960'],
            ['name' => 'Mali', 'code' => 'ML', 'telephoneCode' => '+223'],
            ['name' => 'Malta', 'code' => 'MT', 'telephoneCode' => '+356'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'telephoneCode' => '+692'],
            ['name' => 'Mauritania', 'code' => 'MR', 'telephoneCode' => '+222'],
            ['name' => 'Mauritius', 'code' => 'MU', 'telephoneCode' => '+230'],
            ['name' => 'Mexico', 'code' => 'MX', 'telephoneCode' => '+52'],
            ['name' => 'Micronesia', 'code' => 'FM', 'telephoneCode' => '+691'],
            ['name' => 'Moldova', 'code' => 'MD', 'telephoneCode' => '+373'],
            ['name' => 'Monaco', 'code' => 'MC', 'telephoneCode' => '+377'],
            ['name' => 'Mongolia', 'code' => 'MN', 'telephoneCode' => '+976'],
            ['name' => 'Montenegro', 'code' => 'ME', 'telephoneCode' => '+382'],
            ['name' => 'Morocco', 'code' => 'MA', 'telephoneCode' => '+212'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'telephoneCode' => '+258'],
            ['name' => 'Myanmar', 'code' => 'MM', 'telephoneCode' => '+95'],
            ['name' => 'Namibia', 'code' => 'NA', 'telephoneCode' => '+264'],
            ['name' => 'Nauru', 'code' => 'NR', 'telephoneCode' => '+674'],
            ['name' => 'Nepal', 'code' => 'NP', 'telephoneCode' => '+977'],
            ['name' => 'Netherlands', 'code' => 'NL', 'telephoneCode' => '+31'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'telephoneCode' => '+64'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'telephoneCode' => '+505'],
            ['name' => 'Niger', 'code' => 'NE', 'telephoneCode' => '+227'],
            ['name' => 'Nigeria', 'code' => 'NG', 'telephoneCode' => '+234'],
            ['name' => 'North Korea', 'code' => 'KP', 'telephoneCode' => '+850'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'telephoneCode' => '+389'],
            ['name' => 'Norway', 'code' => 'NO', 'telephoneCode' => '+47'],
            ['name' => 'Oman', 'code' => 'OM', 'telephoneCode' => '+968'],
            ['name' => 'Pakistan', 'code' => 'PK', 'telephoneCode' => '+92'],
            ['name' => 'Palau', 'code' => 'PW', 'telephoneCode' => '+680'],
            ['name' => 'Panama', 'code' => 'PA', 'telephoneCode' => '+507'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'telephoneCode' => '+675'],
            ['name' => 'Paraguay', 'code' => 'PY', 'telephoneCode' => '+595'],
            ['name' => 'Peru', 'code' => 'PE', 'telephoneCode' => '+51'],
            ['name' => 'Philippines', 'code' => 'PH', 'telephoneCode' => '+63'],
            ['name' => 'Poland', 'code' => 'PL', 'telephoneCode' => '+48'],
            ['name' => 'Portugal', 'code' => 'PT', 'telephoneCode' => '+351'],
            ['name' => 'Qatar', 'code' => 'QA', 'telephoneCode' => '+974'],
            ['name' => 'Romania', 'code' => 'RO', 'telephoneCode' => '+40'],
            ['name' => 'Russia', 'code' => 'RU', 'telephoneCode' => '+7'],
            ['name' => 'Rwanda', 'code' => 'RW', 'telephoneCode' => '+250'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'telephoneCode' => '+1'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'telephoneCode' => '+1'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'telephoneCode' => '+1'],
            ['name' => 'Samoa', 'code' => 'WS', 'telephoneCode' => '+685'],
            ['name' => 'San Marino', 'code' => 'SM', 'telephoneCode' => '+378'],
            ['name' => 'São Tomé and Príncipe', 'code' => 'ST', 'telephoneCode' => '+239'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'telephoneCode' => '+966'],
            ['name' => 'Senegal', 'code' => 'SN', 'telephoneCode' => '+221'],
            ['name' => 'Serbia', 'code' => 'RS', 'telephoneCode' => '+381'],
            ['name' => 'Seychelles', 'code' => 'SC', 'telephoneCode' => '+248'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'telephoneCode' => '+232'],
            ['name' => 'Singapore', 'code' => 'SG', 'telephoneCode' => '+65'],
            ['name' => 'Slovakia', 'code' => 'SK', 'telephoneCode' => '+421'],
            ['name' => 'Slovenia', 'code' => 'SI', 'telephoneCode' => '+386'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'telephoneCode' => '+677'],
            ['name' => 'Somalia', 'code' => 'SO', 'telephoneCode' => '+252'],
            ['name' => 'South Africa', 'code' => 'ZA', 'telephoneCode' => '+27'],
            ['name' => 'South Korea', 'code' => 'KR', 'telephoneCode' => '+82'],
            ['name' => 'South Sudan', 'code' => 'SS', 'telephoneCode' => '+211'],
            ['name' => 'Spain', 'code' => 'ES', 'telephoneCode' => '+34'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'telephoneCode' => '+94'],
            ['name' => 'Sudan', 'code' => 'SD', 'telephoneCode' => '+249'],
            ['name' => 'Suriname', 'code' => 'SR', 'telephoneCode' => '+597'],
            ['name' => 'Sweden', 'code' => 'SE', 'telephoneCode' => '+46'],
            ['name' => 'Switzerland', 'code' => 'CH', 'telephoneCode' => '+41'],
            ['name' => 'Syria', 'code' => 'SY', 'telephoneCode' => '+963'],
            ['name' => 'Taiwan', 'code' => 'TW', 'telephoneCode' => '+886'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'telephoneCode' => '+992'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'telephoneCode' => '+255'],
            ['name' => 'Thailand', 'code' => 'TH', 'telephoneCode' => '+66'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'telephoneCode' => '+670'],
            ['name' => 'Togo', 'code' => 'TG', 'telephoneCode' => '+228'],
            ['name' => 'Tonga', 'code' => 'TO', 'telephoneCode' => '+676'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'telephoneCode' => '+1'],
            ['name' => 'Tunisia', 'code' => 'TN', 'telephoneCode' => '+216'],
            ['name' => 'Turkey', 'code' => 'TR', 'telephoneCode' => '+90'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'telephoneCode' => '+993'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'telephoneCode' => '+688'],
            ['name' => 'Uganda', 'code' => 'UG', 'telephoneCode' => '+256'],
            ['name' => 'Ukraine', 'code' => 'UA', 'telephoneCode' => '+380'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'telephoneCode' => '+971'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'telephoneCode' => '+44'],
            ['name' => 'United States', 'code' => 'US', 'telephoneCode' => '+1'],
            ['name' => 'Uruguay', 'code' => 'UY', 'telephoneCode' => '+598'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'telephoneCode' => '+998'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'telephoneCode' => '+678'],
            ['name' => 'Vatican City', 'code' => 'VA', 'telephoneCode' => '+39'],
            ['name' => 'Venezuela', 'code' => 'VE', 'telephoneCode' => '+58'],
            ['name' => 'Vietnam', 'code' => 'VN', 'telephoneCode' => '+84'],
            ['name' => 'Yemen', 'code' => 'YE', 'telephoneCode' => '+967'],
            ['name' => 'Zambia', 'code' => 'ZM', 'telephoneCode' => '+260'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'telephoneCode' => '+263'],
        ];

        $countriesWithFlags = array_map(function($country) {
            $flag = $this->getFlagEmoji($country['code']);
            return [
                'name' => $country['name'],
                'code' => $country['code'],
                'telephoneCode' => $country['telephoneCode'],
                'flag' => $flag,
            ];
        }, $countries);

        return $this->json($countriesWithFlags);
    }

    #[Route('/api/country-codes', name: 'api_country_codes', methods: ['GET'])]
    public function getCountryCodes(): JsonResponse
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'telephoneCode' => '+93'],
            ['name' => 'Albania', 'code' => 'AL', 'telephoneCode' => '+355'],
            ['name' => 'Algeria', 'code' => 'DZ', 'telephoneCode' => '+213'],
            ['name' => 'Andorra', 'code' => 'AD', 'telephoneCode' => '+376'],
            ['name' => 'Angola', 'code' => 'AO', 'telephoneCode' => '+244'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'telephoneCode' => '+1'],
            ['name' => 'Argentina', 'code' => 'AR', 'telephoneCode' => '+54'],
            ['name' => 'Armenia', 'code' => 'AM', 'telephoneCode' => '+374'],
            ['name' => 'Australia', 'code' => 'AU', 'telephoneCode' => '+61'],
            ['name' => 'Austria', 'code' => 'AT', 'telephoneCode' => '+43'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'telephoneCode' => '+994'],
            ['name' => 'Bahamas', 'code' => 'BS', 'telephoneCode' => '+1'],
            ['name' => 'Bahrain', 'code' => 'BH', 'telephoneCode' => '+973'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'telephoneCode' => '+880'],
            ['name' => 'Barbados', 'code' => 'BB', 'telephoneCode' => '+1'],
            ['name' => 'Belarus', 'code' => 'BY', 'telephoneCode' => '+375'],
            ['name' => 'Belgium', 'code' => 'BE', 'telephoneCode' => '+32'],
            ['name' => 'Belize', 'code' => 'BZ', 'telephoneCode' => '+501'],
            ['name' => 'Benin', 'code' => 'BJ', 'telephoneCode' => '+229'],
            ['name' => 'Bhutan', 'code' => 'BT', 'telephoneCode' => '+975'],
            ['name' => 'Bolivia', 'code' => 'BO', 'telephoneCode' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'telephoneCode' => '+387'],
            ['name' => 'Botswana', 'code' => 'BW', 'telephoneCode' => '+267'],
            ['name' => 'Brazil', 'code' => 'BR', 'telephoneCode' => '+55'],
            ['name' => 'Brunei', 'code' => 'BN', 'telephoneCode' => '+673'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'telephoneCode' => '+359'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'telephoneCode' => '+226'],
            ['name' => 'Burundi', 'code' => 'BI', 'telephoneCode' => '+257'],
            ['name' => 'Cambodia', 'code' => 'KH', 'telephoneCode' => '+855'],
            ['name' => 'Cameroon', 'code' => 'CM', 'telephoneCode' => '+237'],
            ['name' => 'Canada', 'code' => 'CA', 'telephoneCode' => '+1'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'telephoneCode' => '+238'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'telephoneCode' => '+236'],
            ['name' => 'Chad', 'code' => 'TD', 'telephoneCode' => '+235'],
            ['name' => 'Chile', 'code' => 'CL', 'telephoneCode' => '+56'],
            ['name' => 'China', 'code' => 'CN', 'telephoneCode' => '+86'],
            ['name' => 'Colombia', 'code' => 'CO', 'telephoneCode' => '+57'],
            ['name' => 'Comoros', 'code' => 'KM', 'telephoneCode' => '+269'],
            ['name' => 'Congo (Brazzaville)', 'code' => 'CG', 'telephoneCode' => '+242'],
            ['name' => 'Congo (Kinshasa)', 'code' => 'CD', 'telephoneCode' => '+243'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'telephoneCode' => '+506'],
            ['name' => 'Croatia', 'code' => 'HR', 'telephoneCode' => '+385'],
            ['name' => 'Cuba', 'code' => 'CU', 'telephoneCode' => '+53'],
            ['name' => 'Cyprus', 'code' => 'CY', 'telephoneCode' => '+357'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'telephoneCode' => '+420'],
            ['name' => 'Denmark', 'code' => 'DK', 'telephoneCode' => '+45'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'telephoneCode' => '+253'],
            ['name' => 'Dominica', 'code' => 'DM', 'telephoneCode' => '+1'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'telephoneCode' => '+1'],
            ['name' => 'Ecuador', 'code' => 'EC', 'telephoneCode' => '+593'],
            ['name' => 'Egypt', 'code' => 'EG', 'telephoneCode' => '+20'],
            ['name' => 'El Salvador', 'code' => 'SV', 'telephoneCode' => '+503'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'telephoneCode' => '+240'],
            ['name' => 'Eritrea', 'code' => 'ER', 'telephoneCode' => '+291'],
            ['name' => 'Estonia', 'code' => 'EE', 'telephoneCode' => '+372'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'telephoneCode' => '+251'],
            ['name' => 'Fiji', 'code' => 'FJ', 'telephoneCode' => '+679'],
            ['name' => 'Finland', 'code' => 'FI', 'telephoneCode' => '+358'],
            ['name' => 'France', 'code' => 'FR', 'telephoneCode' => '+33'],
            ['name' => 'Gabon', 'code' => 'GA', 'telephoneCode' => '+241'],
            ['name' => 'Gambia', 'code' => 'GM', 'telephoneCode' => '+220'],
            ['name' => 'Georgia', 'code' => 'GE', 'telephoneCode' => '+995'],
            ['name' => 'Germany', 'code' => 'DE', 'telephoneCode' => '+49'],
            ['name' => 'Ghana', 'code' => 'GH', 'telephoneCode' => '+233'],
            ['name' => 'Greece', 'code' => 'GR', 'telephoneCode' => '+30'],
            ['name' => 'Grenada', 'code' => 'GD', 'telephoneCode' => '+1'],
            ['name' => 'Guatemala', 'code' => 'GT', 'telephoneCode' => '+502'],
            ['name' => 'Guinea', 'code' => 'GN', 'telephoneCode' => '+224'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'telephoneCode' => '+245'],
            ['name' => 'Guyana', 'code' => 'GY', 'telephoneCode' => '+592'],
            ['name' => 'Haiti', 'code' => 'HT', 'telephoneCode' => '+509'],
            ['name' => 'Honduras', 'code' => 'HN', 'telephoneCode' => '+504'],
            ['name' => 'Hungary', 'code' => 'HU', 'telephoneCode' => '+36'],
            ['name' => 'Iceland', 'code' => 'IS', 'telephoneCode' => '+354'],
            ['name' => 'India', 'code' => 'IN', 'telephoneCode' => '+91'],
            ['name' => 'Indonesia', 'code' => 'ID', 'telephoneCode' => '+62'],
            ['name' => 'Iran', 'code' => 'IR', 'telephoneCode' => '+98'],
            ['name' => 'Iraq', 'code' => 'IQ', 'telephoneCode' => '+964'],
            ['name' => 'Ireland', 'code' => 'IE', 'telephoneCode' => '+353'],
            ['name' => 'Israel', 'code' => 'IL', 'telephoneCode' => '+972'],
            ['name' => 'Italy', 'code' => 'IT', 'telephoneCode' => '+39'],
            ['name' => 'Jamaica', 'code' => 'JM', 'telephoneCode' => '+1'],
            ['name' => 'Japan', 'code' => 'JP', 'telephoneCode' => '+81'],
            ['name' => 'Jordan', 'code' => 'JO', 'telephoneCode' => '+962'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'telephoneCode' => '+7'],
            ['name' => 'Kenya', 'code' => 'KE', 'telephoneCode' => '+254'],
            ['name' => 'Kiribati', 'code' => 'KI', 'telephoneCode' => '+686'],
            ['name' => 'Kuwait', 'code' => 'KW', 'telephoneCode' => '+965'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'telephoneCode' => '+996'],
            ['name' => 'Laos', 'code' => 'LA', 'telephoneCode' => '+856'],
            ['name' => 'Latvia', 'code' => 'LV', 'telephoneCode' => '+371'],
            ['name' => 'Lebanon', 'code' => 'LB', 'telephoneCode' => '+961'],
            ['name' => 'Lesotho', 'code' => 'LS', 'telephoneCode' => '+266'],
            ['name' => 'Liberia', 'code' => 'LR', 'telephoneCode' => '+231'],
            ['name' => 'Libya', 'code' => 'LY', 'telephoneCode' => '+218'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'telephoneCode' => '+423'],
            ['name' => 'Lithuania', 'code' => 'LT', 'telephoneCode' => '+370'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'telephoneCode' => '+352'],
            ['name' => 'Madagascar', 'code' => 'MG', 'telephoneCode' => '+261'],
            ['name' => 'Malawi', 'code' => 'MW', 'telephoneCode' => '+265'],
            ['name' => 'Malaysia', 'code' => 'MY', 'telephoneCode' => '+60'],
            ['name' => 'Maldives', 'code' => 'MV', 'telephoneCode' => '+960'],
            ['name' => 'Mali', 'code' => 'ML', 'telephoneCode' => '+223'],
            ['name' => 'Malta', 'code' => 'MT', 'telephoneCode' => '+356'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'telephoneCode' => '+692'],
            ['name' => 'Mauritania', 'code' => 'MR', 'telephoneCode' => '+222'],
            ['name' => 'Mauritius', 'code' => 'MU', 'telephoneCode' => '+230'],
            ['name' => 'Mexico', 'code' => 'MX', 'telephoneCode' => '+52'],
            ['name' => 'Micronesia', 'code' => 'FM', 'telephoneCode' => '+691'],
            ['name' => 'Moldova', 'code' => 'MD', 'telephoneCode' => '+373'],
            ['name' => 'Monaco', 'code' => 'MC', 'telephoneCode' => '+377'],
            ['name' => 'Mongolia', 'code' => 'MN', 'telephoneCode' => '+976'],
            ['name' => 'Montenegro', 'code' => 'ME', 'telephoneCode' => '+382'],
            ['name' => 'Morocco', 'code' => 'MA', 'telephoneCode' => '+212'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'telephoneCode' => '+258'],
            ['name' => 'Myanmar', 'code' => 'MM', 'telephoneCode' => '+95'],
            ['name' => 'Namibia', 'code' => 'NA', 'telephoneCode' => '+264'],
            ['name' => 'Nauru', 'code' => 'NR', 'telephoneCode' => '+674'],
            ['name' => 'Nepal', 'code' => 'NP', 'telephoneCode' => '+977'],
            ['name' => 'Netherlands', 'code' => 'NL', 'telephoneCode' => '+31'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'telephoneCode' => '+64'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'telephoneCode' => '+505'],
            ['name' => 'Niger', 'code' => 'NE', 'telephoneCode' => '+227'],
            ['name' => 'Nigeria', 'code' => 'NG', 'telephoneCode' => '+234'],
            ['name' => 'North Korea', 'code' => 'KP', 'telephoneCode' => '+850'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'telephoneCode' => '+389'],
            ['name' => 'Norway', 'code' => 'NO', 'telephoneCode' => '+47'],
            ['name' => 'Oman', 'code' => 'OM', 'telephoneCode' => '+968'],
            ['name' => 'Pakistan', 'code' => 'PK', 'telephoneCode' => '+92'],
            ['name' => 'Palau', 'code' => 'PW', 'telephoneCode' => '+680'],
            ['name' => 'Panama', 'code' => 'PA', 'telephoneCode' => '+507'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'telephoneCode' => '+675'],
            ['name' => 'Paraguay', 'code' => 'PY', 'telephoneCode' => '+595'],
            ['name' => 'Peru', 'code' => 'PE', 'telephoneCode' => '+51'],
            ['name' => 'Philippines', 'code' => 'PH', 'telephoneCode' => '+63'],
            ['name' => 'Poland', 'code' => 'PL', 'telephoneCode' => '+48'],
            ['name' => 'Portugal', 'code' => 'PT', 'telephoneCode' => '+351'],
            ['name' => 'Qatar', 'code' => 'QA', 'telephoneCode' => '+974'],
            ['name' => 'Romania', 'code' => 'RO', 'telephoneCode' => '+40'],
            ['name' => 'Russia', 'code' => 'RU', 'telephoneCode' => '+7'],
            ['name' => 'Rwanda', 'code' => 'RW', 'telephoneCode' => '+250'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'telephoneCode' => '+1'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'telephoneCode' => '+1'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'telephoneCode' => '+1'],
            ['name' => 'Samoa', 'code' => 'WS', 'telephoneCode' => '+685'],
            ['name' => 'San Marino', 'code' => 'SM', 'telephoneCode' => '+378'],
            ['name' => 'São Tomé and Príncipe', 'code' => 'ST', 'telephoneCode' => '+239'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'telephoneCode' => '+966'],
            ['name' => 'Senegal', 'code' => 'SN', 'telephoneCode' => '+221'],
            ['name' => 'Serbia', 'code' => 'RS', 'telephoneCode' => '+381'],
            ['name' => 'Seychelles', 'code' => 'SC', 'telephoneCode' => '+248'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'telephoneCode' => '+232'],
            ['name' => 'Singapore', 'code' => 'SG', 'telephoneCode' => '+65'],
            ['name' => 'Slovakia', 'code' => 'SK', 'telephoneCode' => '+421'],
            ['name' => 'Slovenia', 'code' => 'SI', 'telephoneCode' => '+386'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'telephoneCode' => '+677'],
            ['name' => 'Somalia', 'code' => 'SO', 'telephoneCode' => '+252'],
            ['name' => 'South Africa', 'code' => 'ZA', 'telephoneCode' => '+27'],
            ['name' => 'South Korea', 'code' => 'KR', 'telephoneCode' => '+82'],
            ['name' => 'South Sudan', 'code' => 'SS', 'telephoneCode' => '+211'],
            ['name' => 'Spain', 'code' => 'ES', 'telephoneCode' => '+34'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'telephoneCode' => '+94'],
            ['name' => 'Sudan', 'code' => 'SD', 'telephoneCode' => '+249'],
            ['name' => 'Suriname', 'code' => 'SR', 'telephoneCode' => '+597'],
            ['name' => 'Sweden', 'code' => 'SE', 'telephoneCode' => '+46'],
            ['name' => 'Switzerland', 'code' => 'CH', 'telephoneCode' => '+41'],
            ['name' => 'Syria', 'code' => 'SY', 'telephoneCode' => '+963'],
            ['name' => 'Taiwan', 'code' => 'TW', 'telephoneCode' => '+886'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'telephoneCode' => '+992'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'telephoneCode' => '+255'],
            ['name' => 'Thailand', 'code' => 'TH', 'telephoneCode' => '+66'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'telephoneCode' => '+670'],
            ['name' => 'Togo', 'code' => 'TG', 'telephoneCode' => '+228'],
            ['name' => 'Tonga', 'code' => 'TO', 'telephoneCode' => '+676'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'telephoneCode' => '+1'],
            ['name' => 'Tunisia', 'code' => 'TN', 'telephoneCode' => '+216'],
            ['name' => 'Turkey', 'code' => 'TR', 'telephoneCode' => '+90'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'telephoneCode' => '+993'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'telephoneCode' => '+688'],
            ['name' => 'Uganda', 'code' => 'UG', 'telephoneCode' => '+256'],
            ['name' => 'Ukraine', 'code' => 'UA', 'telephoneCode' => '+380'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'telephoneCode' => '+971'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'telephoneCode' => '+44'],
            ['name' => 'United States', 'code' => 'US', 'telephoneCode' => '+1'],
            ['name' => 'Uruguay', 'code' => 'UY', 'telephoneCode' => '+598'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'telephoneCode' => '+998'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'telephoneCode' => '+678'],
            ['name' => 'Vatican City', 'code' => 'VA', 'telephoneCode' => '+39'],
            ['name' => 'Venezuela', 'code' => 'VE', 'telephoneCode' => '+58'],
            ['name' => 'Vietnam', 'code' => 'VN', 'telephoneCode' => '+84'],
            ['name' => 'Yemen', 'code' => 'YE', 'telephoneCode' => '+967'],
            ['name' => 'Zambia', 'code' => 'ZM', 'telephoneCode' => '+260'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'telephoneCode' => '+263'],
        ];

        $countryCodes = array_map(function($country) {
            $flag = $this->getFlagUrl($country['code']);
            return [
                'name' => $country['name'],
                'code' => $country['code'],
                'telephoneCode' => $country['telephoneCode'],
                'flag' => $flag,
            ];
        }, $countries);

        return $this->json($countryCodes);
    }

    private function getFlagUrl(string $countryCode): string
    {
        $code = strtolower($countryCode);
        return "https://flagcdn.com/w320/{$code}.png";
    }

    private function getFlagEmoji(string $countryCode): string
    {
        $code = strtoupper($countryCode);
        if (strlen($code) !== 2) {
            return '';
        }
        $first = ord($code[0]) - ord('A') + 0x1F1E6;
        $second = ord($code[1]) - ord('A') + 0x1F1E6;
        return mb_chr($first, 'UTF-8') . mb_chr($second, 'UTF-8');
    }
}